---
title: Discover Warboys
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: website@warboys.uk
description: The Cambridgeshire village famous for witches trials
baseurl: 
url: 
twitter_username: 
github_username: 
theme: jekyll-theme-yat
plugins:
  - jekyll-feed
  - jemoji
remote_theme: "jeffreytse/jekyll-theme-yat"

author: 
copyright: Copyright © 2021

markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
