---
title: Discover Warboys
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: website@warboys.uk
description: "A website for the village of Warboys in Cambridgeshire. Find information on local amenities, and the history of our village, famous for its witch trials."
baseurl: 
url: https://warboys.uk
twitter_username: 
github_username: warboys-village
theme: jekyll-theme-yat
plugins:
- jekyll-feed
- jemoji
remote_theme: jeffreytse/jekyll-theme-yat
author: Antimatters
copyright: Copyright © 2025
css: /assets/css/style.scss
markdown: CommonMarkGhPages
commonmark:
  options:
  - SMART
  - FOOTNOTES
  extensions:
  - strikethrough
  - autolink
  - table
  - tagfilter
