---
title: Discover Warboys
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: The Cambridgeshire village famous for witches trials
baseurl: 
url: 
twitter_username: 
github_username: 
theme: jekyll-theme-yat
plugins:
- jekyll-feed
remote_theme: jeffreytse/jekyll-theme-yat
