---
title: Discover Warboys
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: website@warboys.uk
description: The Cambridgeshire village famous for witches trials
baseurl: 
url: https://warboys.uk
twitter_username: 
github_username: warboys-village
theme: jekyll-theme-yat
plugins:
- jekyll-feed
- jemoji
remote_theme: jeffreytse/jekyll-theme-yat
author: 
copyright: Copyright © 2021
markdown: CommonMarkGhPages
commonmark:
  options:
  - SMART
  - FOOTNOTES
  extensions:
  - strikethrough
  - autolink
  - table
  - tagfilter
