name: Deploy Eleventy to GitHub Pages

on:
  push:
    branches:
      - main # Set a branch to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18 # Use the Node.js version specified in your package.json or a suitable LTS version

      - name: Install dependencies
        run: npm install

      - name: Build Eleventy
        run: npm run build # Or 'npx eleventy' if you don't have a build script

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site # The directory where Eleventy outputs your built site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
